### ISSUE TITLE
Doesn't report tags in test directory

### ISSUE THREAD

**Issue by ViliusN** [johanandren/sbt-taglist#13]
TODO tags in test directory are not reported

**Comment by johanandren** [comment]
Indeed, hardcoded to `sources in Compile`, right now. Not sure the default should be different, but maybe allow for configuration of what sources it goes through?

**Comment by johanandren** [comment]
Or provide scoped tasks, so that `tagList` lists source todos and `test:tagList` lists test source todos?

**Comment by ViliusN** [comment]
Either way is good, but I can't think of any reason not to report tags from test directory by default

**Comment by johanandren** [comment]
Because you would maybe want to fail the build on FIXMES/TODOs in prod code, but not in test code?

**Comment by ViliusN** [comment]
Don't mean to nag or anything, but... Is there any chance to see this implemented in (nearish) future?

**Comment by ViliusN** [comment]
By the way, your competitors have done this right: https://github.com/fedragon/sbt-todolist
:)

**Comment by johanandren** [comment]
Great for you that it does what you want! If you do not want to switch, PRs are welcome, I'm afraid I'm of busy with other things.
